app/Posts/routes.py
import re
from flask import render_template, url_for, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt, mail
from flask import render_template, Blueprint, url_for, flash, redirect, request
from app.Users.utils import save_postsImage
from app.models import Complaints, Receipts, Notice, ToLet
from app.Posts.forms import ReceiptForm, NoticeForm, ComplaintsForm, ToletForm


posts = Blueprint('posts', __name__)


@posts.route('/create/receipt', methods=['POST', 'GET'])
@login_required
def create():
    form = ReceiptForm()
    if form.validate_on_submit():
        picture = save_postsImage(form.receipt_image.data)

        receipt = Receipts(
            account_number=form.account_number.data, user_id=current_user.id,
            amount=form.amount.data, receipt_image=picture, date_paid=form.date_paid.data)
        db.session.add(receipt)
        db.session.commit()
        flash('your receipt has been uploaded successfully')
        return redirect(url_for('main.home'))
    return render_template('receipts.html', form=form, title="New receipt")


@posts.route('/all/receipts', methods=['POST', 'GET'])
@login_required
def all_receipts():
    receipt = Receipts.query.all()
    for r in receipt:
        image_file = url_for('static', filename='posts/'+r.receipt_image)

        r.receipt_image = image_file
    return render_template('allreceipts.html', receipt=receipt)


@posts.route('/notice', methods=['GET', 'POST'])
@login_required
def notice():
    form = NoticeForm()
    if form.validate_on_submit():

        notice = Notice(title=form.title.data,
                        content=form.content.data, user_id=current_user.id,)
        db.session.add(notice)
        db.session.commit()
        flash('your notice has been uploaded successfully')
        return redirect(url_for('main.home'))
    return render_template('notice.html', form=form, title="New Notice")


@posts.route('/create/complaints', methods=['GET', 'POST'])
@login_required
def create_complaints():
    form = ComplaintsForm()
    if form.validate_on_submit():

        notice = Complaints(title=form.title.data,
                            content=form.content.data, user_id=current_user.id,)
        db.session.add(notice)
        db.session.commit()
        flash('your Complaint has been sent')
        return redirect(url_for('main.home'))
    return render_template('complaints.html', form=form, title="New Complaint")


@posts.route('/create/house', methods=['GET', 'POST'])
@login_required
def create_house():
    form = ToletForm()
    if form.validate_on_submit():

        notice = ToLet(houseType=form.houseType.data, description=form.description.data,
                       rent=form.rent.data, user_id=current_user.id,)
        db.session.add(notice)
        db.session.commit()
        flash('Your House To let has been sent')
        return redirect(url_for('main.home'))
    return render_template('houses.html', form=form, title="New House")

app/templates/account.html
{% extends 'base.html' %}
{% block body %}
{% from 'bootstrap5/form.html' import render_form %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="container-fluid row p-5">
        <div class="col-md-4">
          <img src="{{image_file}}" class="img-thumbnail img-fluid border border-white" alt="Profile picture">
        </div>
        <div class="col-md-8 mx-auto mt-auto mb-auto  lead">
          <p> <span class="h5">Username : </span><span>{{ current_user.username.title() }}</span></p>

          <p> <span class="h5">Email : </span><span>{{ current_user.email }}</span></p>
          <p><span class="h5">Type of user : </span><span>{{current_user.typeUser}}</span></p>
          <a data-bs-toggle="collapse" href="#coll" class="text-decoration-none text-muted"> <button
              class="btn btn-secondary">Update Info</button></a>

        </div>
      </div>
      <div class="container-fluid collapse" id="coll">
        {{render_form(form)}}
      </div>
    </div>
    {% if current_user.typeUser=="Tenant" %}
    <div class="col-md-6">
      <p class="display-6 text-center">
        My complaints
      </p>
      <div class="container-fluid d-flex flex-wrap flex-row justify-content-center">
        {% for post in post %}
        <div class=" complaints card  m-4">

          <div class="row  p-2">
            <div class="col-md-7 mx-auto mt-auto mb-auto">
              {% if current_user.id == post.complaintauthor.id %}
              <div class="d-inline mx-3">

              </div>
              {% endif %}

              <p class="d-inline">{{post.category}}</p>
            </div>
            <div class="col-md-2">
              <img src="{{url_for('static', filename='/profiles/'+post.complaintauthor.image_file)}}"
                class="img-thumbnail img-fluid border border-white" alt="Profile picture">
            </div>
            <div class="col-md-3 mx-auto mt-auto mb-auto text-muted">
              <small>{{post.complaintauthor.username}}</small>
              <br>
              <small>{{post.date_created.strftime('%Y-%m-%d')}}</small>
            </div>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text lead">{{post.content}}</p>
            <div class="d-flex justify-content-around">
              <a data-bs-toggle="collapse" href="#complaints{{post.id}}" class="lead text-decoration-none">
                <img src="{{url_for('static',filename='/static/comment.svg')}}" height="30" alt="">
              </a>
            </div>
            <div class="collapse" id="complaints{{post.id}}">

              <div class=" complaints my-3">
                <p>Complaints</p>
                <div class="card m-1">
                  {% for com in post.complaints %}
                  <div class="d-flex justify-content-between">

                    <p class="lead fst-italic ">

                      {{com.complaints}}
                      <div>

                        {% if current_user.id == post.author.id %}

                        {% endif %}
                      </div>
                    </p>
                  </div>
                  {% endfor %}
                </div>
              </div>

             
            </div>
          </div>

        </div>

        {% endfor %}

      </div>
    </div>
    {% else %}
    <div class="col-md-6">
      <p class="display-6 text-center">
        My Notices
      </p>
      <div class="container-fluid d-flex flex-wrap flex-row justify-content-center">
        {% for notice in notice %}
        <div class=" complaints card  m-4">

          <div class="row  p-2">
            <div class="col-md-7 mx-auto mt-auto mb-auto">
              {% if current_user.id == notice.noticeAuthor.id %}
              <div class="d-inline mx-3">

              </div>
              {% endif %}

            </div>
            <div class="col-md-2">
              <img src="{{url_for('static', filename='/profiles/'+notice.noticeAuthor.image_file)}}"
                class="img-thumbnail img-fluid border border-white" alt="Profile picture">
            </div>
            <div class="col-md-3 mx-auto mt-auto mb-auto text-muted">
              <small>{{notice.noticeAuthor.username}}</small>
              <br>
              <small>{{notice.date_created.strftime('%Y-%m-%d')}}</small>
            </div>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{notice.title}}</h5>
            <p class="card-text lead">{{notice.content}}</p>
           
          
          </div>

        </div>

        {% endfor %}

      </div>
    </div>
    {% endif %}



  </div>
</div>
{%endblock%}

app/templates/allreceipts.html
{% extends 'base.html' %}

{% block body %}

{% for receipt in receipt %}
<p>{{receipt.amount}}</p>

{% endfor %}

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS only -->
  <link href='https://fonts.googleapis.com/css?family=Sacramento' rel='stylesheet'>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">

  <title>{{title}}</title>
</head>

<body>
  <!-- Nav Bar------------------------------------------------ -->



  {% block navbar %}
  {% if request.url_rule.endpoint != 'users.register' and request.url_rule.endpoint != 'users.login' %}

  {% include 'nav.html' %}
  {% endif %}


  {% endblock %}


  {% with messages = get_flashed_messages(with_categories = true) %}
  {% if messages %}
  {%for category,message in messages %}
  <div class="alert alert-{{ category }} alert-dismissible fade show">{{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {%endfor%}
  {% endif %}
  {% endwith %}

  {% block body %}

  {% endblock %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

</body>

</html>

app/templates/complaints.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid my-5">
  <div class="container  receipt-form mt-2 p-3 w-50">
    <form action="" method="post" enctype="multipart/form-data" class="p-5">
      {{form.hidden_tag()}}
      <h3 class="text-center text-white">File Complaint</h3>

          <div class="form-group">
            {{form.title.label(class='form-control-label text-white')}}
            {% if form.title.errors %}
            {{form.title(class='form-control is-invalid')}}
            {% for error in form.title.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.title(class='form-control bg-transparent text-white',placeholder="Enter The Title")}}
            {% endif %}
          </div>
          <div class="form-group mt-3">
            {{form.content.label(class='form-control-label text-white')}}
            {% if form.content.errors %}
            {{form.content(class='form-control is-invalid ')}}
            {% for error in form.content.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.content(class='form-control bg-transparent text-white',placeholder="Enter Description")}}
            {% endif %}
          </div>
          <div class="text-center mt-5">
            {{form.submit(class='btn btn-outline receipt_submit')}}
          </div>
        </div>
         

    
    </form>

  </div>
</div>
{% endblock %}

app/templates/createCaretaker.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid my-3">
  <div class="container  receipt-form mt-2 p-3 w-50">
    <form action="" method="post" enctype="multipart/form-data" class="p-5">
      {{form.hidden_tag()}}
      <h3 class="text-center text-white">Create Caretaker</h3>

      <div class="form-group">
        {{form.username.label(class='form-control-label text-white')}}
        {% if form.username.errors %}
        {{form.username(class='form-control is-invalid')}}
        {% for error in form.username.errors %}
        <div class="invalid-feedback">
          {{error}}
        </div>
        {% endfor %}
        {% else %}
        {{form.username(class='form-control bg-transparent text-white',placeholder="Enter username")}}
        {% endif %}
      </div>
      <div class="form-group mt-3">
        {{form.email.label(class='form-control-label text-white')}}
        {% if form.email.errors %}
        {{form.email(class='form-control is-invalid ')}}
        {% for error in form.email.errors %}
        <div class="invalid-feedback">
          {{error}}
        </div>
        {% endfor %}
        {% else %}
        {{form.email(class='form-control bg-transparent text-white',placeholder="Enter email")}}
        {% endif %}
      </div>
      <div class="form-group mt-3">
        {{form.phoneNumber.label(class='form-control-label')}}
        {% if form.phoneNumber.errors %}
        {{form.phoneNumber(class='form-control is-invalid')}}
        {% for error in form.phoneNumber.errors %}
        <div class="invalid-feedback">
          {{error}}
        </div>
        {% endfor %}
        {% else %}
        {{form.phoneNumber(class='form-control bg-transparent all_border mb-2',placeholder="Enter Phone Number")}}
        {% endif %}
      </div>
      <div class="form-group mt-3">
        {{form.password.label(class='form-control-label text-white')}}
        {% if form.password.errors %}
        {{form.password(class='form-control is-invalid ')}}
        {% for error in form.password.errors %}
        <div class="invalid-feedback">
          {{error}}
        </div>
        {% endfor %}
        {% else %}
        {{form.password(class='form-control bg-transparent text-white',placeholder="Enter password")}}
        {% endif %}
      </div>
      <div class="form-group mt-3">
        {{form.confirm_password.label(class='form-control-label text-white')}}
        {% if form.confirm_password.errors %}
        {{form.confirm_password(class='form-control is-invalid ')}}
        {% for error in form.confirm_password.errors %}
        <div class="invalid-feedback">
          {{error}}
        </div>
        {% endfor %}
        {% else %}
        {{form.confirm_password(class='form-control bg-transparent text-white',placeholder="Enter confirm password")}}
        {% endif %}
      </div>

      <div class="text-center mt-3">
        {{form.submit(class='btn btn-outline receipt_submit')}}
      </div>
  </div>
  </form>

</div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-6 ">
      <p class="h3"> Apollo Apartments</p>
      <p> We provide the best housing facilities and are concenered <br>
        about your time here. This is your tool to make living here so <br> much easier</p>

      <a href="{{url_for('posts.create')}}"><button class="btn btn-secondary mt-4">Upload Receipt</button></a>
    </div>
    <div class="col-md-6">
      <img src="./../static/landingPage.png" alt="">
    </div>
  </div>

  <p class="h3 mb-3">N<u class="sect">otic</u>es</p>

  <div class="row">
    {% for notice in notice %}
    <div class="col-md-4">
      <div class="card notice my-3" style="width: 23rem;">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">{{notice.noticeAuthor.username}}</div>
          </div>
          <h5 class="card-title">{{notice.title}}</h5>
          <p class="card-text">{{notice.content}}</p>

        </div>
      </div>

    </div>
    {% endfor %}

  </div>
  <p class="h3 mb-5 mt-3">Co<u class="sect">mplai</u>nts</p>


  <div class="row mb-5 mt-3">
    {% for complaint in complaint %}
    <div class="col-md-6">
      <div class="card complaint my-3" style="width: 23rem;">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">{{complaint.letAuthor.username}}</div>
          </div>
          <h5 class="card-title">{{complaint.title}}</h5>
          <p class="card-text">{{complaint.content}}</p>

        </div>
      </div>

    </div>
    {% endfor %}
  </div>

  <p class="h3 mb-5">Hou<u class="sect">ses To </u> Let</p>

  <div class="row my-3 mb-5">
    {% for tolet in tolet %}
    <div class="col-md-6">
      <div class="card house my-3 tolet" style="width: 25rem;">
        <div class="card-body">

          <h5 class="card-title">{{tolet.houseType}}</h5>
          <p class="card-text">{{tolet.description}}</p>
          <div class=" d-flex justify-content-between">
            <p></p>
            <p>Rent {{tolet.rent}} /month</p>

          </div>

        </div>
      </div>

    </div>
    {% endfor %}

  </div>




</div>
<div class="foot">

  <p class="text-white mx-5">Contact Information</p>

  <div class="d-flex mx-5">
    <div>
      <p class="text-white">phone Number</p>
      <p class="text-white">Email</p>

    </div>
    <div>
      <p class="mx-5 text-white">+254071234568</p>

      <p class="mx-5 text-white">managenyumba@gmail.com</p>
    </div>
  </div>
</div>

{% endblock %}

app/templates/houses.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid my-5">
  <div class="container  receipt-form mt-2 p-3 w-50">
    <form action="" method="post" enctype="multipart/form-data" class="p-5">
      {{form.hidden_tag()}}
      <h3 class="text-center text-white">House To let</h3>

          <div class="form-group">
            {{form.houseType.label(class='form-control-label text-white')}}
            {% if form.houseType.errors %}
            {{form.houseType(class='form-control is-invalid')}}
            {% for error in form.houseType.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.houseType(class='form-control bg-transparent text-white',placeholder="Enter the house type")}}
            {% endif %}
          </div>
          <div class="form-group mt-3">
            {{form.description.label(class='form-control-label text-white')}}
            {% if form.description.errors %}
            {{form.description(class='form-control is-invalid ')}}
            {% for error in form.description.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.description(class='form-control bg-transparent text-white',placeholder="Enter Description")}}
            {% endif %}
          </div>
          <div class="form-group mt-3">
            {{form.rent.label(class='form-control-label text-white')}}
            {% if form.rent.errors %}
            {{form.rent(class='form-control is-invalid ')}}
            {% for error in form.rent.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.rent(class='form-control bg-transparent text-white',placeholder="Enter Rent Amount")}}
            {% endif %}
          </div>
          <div class="text-center mt-5">
            {{form.submit(class='btn btn-outline receipt_submit')}}
          </div>
        </div>
         

    
    </form>

  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ user.username }}!</h1>
    {% for user in users %}
    <div><p>{{ user.username }} says: <b>{{ user.id }}</b></p></div>
    {% endfor %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid ps-md-0">
  <div class="row g-0">
    <div class="d-none d-md-flex col-md-4 col-lg-6 login-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="border-bottom" style="font-weight: bold;">Sign In</h3>
              <form action="" method="post">
                {{form.hidden_tag()}}
                <div class="form-group">
                  {{form.email.label(class='form-control-label')}}
                  {% if form.email.errors %}
                  {{form.email(class='form-control is-invalid')}}
                  {% for error in form.email.errors %}
                  <div class="invalid-feedback">
                    {{error}}
                  </div>
                  {% endfor %}
                  {% else %}
                  {{form.email(class='form-control bg-transparent all_border mb-2',placeholder="Enter Email")}}
                  {% endif %}
                </div>
                <div class="form-group my-3">
                  {{form.password.label(class='form-control-label')}}
                  {% if form.password.errors %}
                  {{form.password(class='form-control is-invalid')}}
                  {% for error in form.password.errors %}
                  <div class="invalid-feedback">
                    {{error}}
                  </div>
                  {% endfor %}
                  {% else %}
                  {{form.password(class='form-control bg-transparent all_border mb-2',placeholder="Enter Password")}}
                  {% endif %}
                </div>
                <!-- Remember -->
                <div class="form-check form-switch">
                  {{form.remember.label(class='form-check-label')}}
                  {{form.remember(class="form-check-input")}}
                </div>
                <div class="text-center mt-3">
                  {{form.submit(class='btn btn-outline btn btn-outline btn-login form-control')}}
                </div>
                <small class="text-muted ml-2 ">
                </small>
              </form>
              <div class="text-muted ">
                <small>Need an account ? <a href="{{url_for('users.register')}}">Sign Up</a></small>
              </div>
              <div class="text-muted ">
                <small>Go back to main  ? <a href="{{url_for('main.home')}}">Home</a></small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/nav.html
     <div class="container">
       <nav class="navbar navbar-expand-lg mt-3">
         <a class="navbar-brand h3" href="{{url_for('main.home')}}">Manage Nyumba</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
           aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse justify-content-evenly " id="navbarNav">
           <ul class="navbar-nav">
             <li class="nav-item">
               <a class="nav-link active mx-2" aria-current="page" href="{{url_for('main.home')}}">Home</a>
             </li>
             {% if current_user.typeUser=='Caretaker' %}
             <li class="nav-item">
               <a class="nav-link active" href="{{url_for('posts.create_house')}}">To let</a>
             </li>
             <li class="nav-item">
               <a class="nav-link active" href="{{url_for('posts.notice')}}">Notice</a>
             </li>
             <li class="nav-item">
               <a class="nav-link active" href="{{url_for('users.register_caretaker')}}">Caretaker</a>
             </li>
             {% endif %}

             {% if current_user.is_authenticated %}

             <li class="nav-item">
               <a class="nav-link active mx-2" href="{{url_for('posts.create_complaints')}}">Complaints</a>
             </li>
             <a class="nav-link active" href="{{url_for('users.account')}}">Account</a>
             <a class="nav-link active" href="{{url_for('users.logout')}}">Logout</a>

             {%else%}
             <li class="nav-item">
               <a class="nav-link active mx-2" href="{{url_for('users.register')}}">Register</a>
             </li>
             <li class="nav-item">
               <a class="nav-link active" href="{{url_for('users.login')}}">Login</a>
             </li>

             {% endif %}

           </ul>
         </div>
     </div>
     </nav>
     </div>

app/templates/notice.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid my-5">
  <div class="container  receipt-form mt-2 p-3 w-50">
    <form action="" method="post" enctype="multipart/form-data" class="p-5">
      {{form.hidden_tag()}}
      <h3 class="text-center text-white">Create Notice</h3>

          <div class="form-group">
            {{form.title.label(class='form-control-label text-white')}}
            {% if form.title.errors %}
            {{form.title(class='form-control is-invalid')}}
            {% for error in form.title.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.title(class='form-control bg-transparent text-white',placeholder="Enter The Title")}}
            {% endif %}
          </div>
          <div class="form-group mt-3">
            {{form.content.label(class='form-control-label text-white')}}
            {% if form.content.errors %}
            {{form.content(class='form-control is-invalid ')}}
            {% for error in form.content.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.content(class='form-control bg-transparent text-white',placeholder="Enter Description")}}
            {% endif %}
          </div>
          <div class="text-center mt-5">
            {{form.submit(class='btn btn-outline receipt_submit')}}
          </div>
        </div>
         

    
    </form>

  </div>
</div>
{% endblock %}

app/templates/receipts.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid my-5">
  <div class="container  receipt-form mt-2 p-3 w-80">
    <form action="" method="post" enctype="multipart/form-data" class="p-5">
      {{form.hidden_tag()}}
      <!-- <h3 class="text-center">Create Blog</h3> -->
      <div class="row mb-3">

        <div class="col-md-6">
          <div class="form-group">
            {{form.account_number.label(class='form-control-label text-white')}}
            {% if form.account_number.errors %}
            {{form.account_number(class='form-control is-invalid')}}
            {% for error in form.account_number.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.account_number(class='form-control bg-transparent text-white',placeholder="Enter Account Number")}}
            {% endif %}
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            {{form.amount.label(class='form-control-label text-white')}}
            {% if form.amount.errors %}
            {{form.amount(class='form-control is-invalid ')}}
            {% for error in form.amount.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.amount(class='form-control bg-transparent text-white',placeholder="Enter Rent Amount")}}
            {% endif %}
          </div>
        </div>
      </div>
      <div class="row">

        <div class="col-md-6">
          <div class="form-group">
            {{form.date_paid.label(class='form-control-label text-white')}}
            {% if form.date_paid.errors %}
            {{form.date_paid(class='form-control is-invalid')}}
            {% for error in form.date_paid.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.date_paid(class='form-control bg-transparent choose text-white',placeholder="Choose the date of payment")}}
            {% endif %}
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            {{form.receipt_image.label(class='form-control-label text-white')}}
            {% if form.receipt_image.errors %}
            {{form.receipt_image(class='form-control is-invalid')}}
            {% for error in form.receipt_image.errors %}
            <div class="invalid-feedback">
              {{error}}
            </div>
            {% endfor %}
            {% else %}
            {{form.receipt_image(class='form-control bg-transparent choose place text-white',placeholder="Choose a receipt image")}}
            {% endif %}
          </div>
        </div>
      </div>


      <div class="text-center mt-5">
        {{form.submit(class='btn btn-outline receipt_submit')}}
      </div>
    </form>

  </div>
</div>
{% endblock %}